### ISSUE TITLE
How to change font size or colour to selected label?

### ISSUE THREAD

**Issue by zeropt7** [kcandr/IQLabelView#3]
Hi, thank you for your code, good work!

I would like to know how to change the font size and colour to selected label, can you please provide me with source code?

Thank you.

**Comment by kcandr** [comment]
@zeropt7 Hi!
1) For change font size you can use **setFontSize** method of selected label
`[selectedLabel setFontSize:pointSize];`
or standard **setFont** method of selected labels textView
`selectedLabel.textView.font = [UIFont fontWithName:fontName size:fontSize];`

2) For change color you can use standard **setTextColor** of selected labels textView
`selectedLabel.textView.textColor = [UIColor redColor];`

I think I will add the option to change colors and make textView property private today. So it will be correctly.
Thank you for your question.

**Comment by zeropt7** [comment]
Thank you so much.
I'll wait for your update today.

**Comment by kcandr** [comment]
@zeropt7 try it now ;)

**Comment by zeropt7** [comment]
@kcandr Thank you so much!
It's working now ;)
