### ISSUE TITLE
Restrict labels to remain within a desired region/view.

### ISSUE THREAD

**Issue by thedp** [kcandr/IQLabelView#4]
This is a very useful controller. It would be even more useful if it supported gesture restriction for a specified view.

**Comment by kcandr** [comment]
Hi @thedp,
Can you explain in more detail? I'm sorry, but I don't quite understand what you mean by "gesture restriction".

**Comment by thedp** [comment]
I'll try to explain.
Let's say I have a UIImageView, and I want the labels to be placed only within the region of that specific view. Currently, the controller allows the dragging of the label anywhere on the screen.

**Comment by kcandr** [comment]
Ok,  I thought so.

**Comment by TomorJM** [comment]
i hope too

**Comment by kcandr** [comment]
@thedp I have added property `enableMoveRestriction` in last version and update demo
