### ISSUE TITLE
Break down with multiple labels

### ISSUE THREAD

**Issue by kcandr** [kcandr/IQLabelView#6]
@tormorOoO `hello IQLabel is really cool. but it has a bug. For example ,if you create two labels,when you create the second one,it become the first responder,then you delete the second one and directly click on the first one(not click on the view and then click on the first one),it will break down at the line "[_textView resignFirstResponder]; it will helpful if you fix it."`
Apparently you are using an older version. I do not like to say it, but I could not reproduce this bug. Try the latest version and let me know if this happens again.

**Comment by TomorJM** [comment]
@kcandr i am sure that i downloaded the latest version and use the latest ios SDK 8.1.
however  it happened again.

**Comment by kcandr** [comment]
@tormorOoO it's in `- (void)hideEditingHandles` method?  I can't reproduce this :unamused:  Can you send stack trace?
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/1710081/8103823/42c6ab02-1034-11e5-93af-4c8d44313876.gif)

**Comment by TomorJM** [comment]
@kcandr  i am so sorry wasting your time . but it is strange  that  i  firstly opened  the control without  the car there  is the bug i have ever mentioned ,however tonight when i opened  the project,the controller was  just like the one in your gif.
thank you all the same.
By the way,if i do not want the label to expand and contract,how can i do that ?

**Comment by kcandr** [comment]
@tormorOoO just set `enableRotate` property to `NO` state
